name: Template Sync
on:
  schedule:
  - cron:  "0 16 * * *"
  workflow_dispatch:
jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check WORKFLOW_TOKEN secret
        id: workflow-token-check
        shell: bash
        run: |
          if [ "${{ secrets.WORKFLOW_TOKEN }}" != '' ]; then
            echo "available=true" >> $GITHUB_OUTPUT;
          else
            echo "available=false" >> $GITHUB_OUTPUT;
          fi
          
  repo-sync:
    needs: check-secret
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: read
    if: ${{ needs.check-secret.outputs.available != 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Sync from template
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: mementomoryn/rmm
          upstream_branch: main
          pr_labels: template_sync
          is_force_push_pr: true
