name: Template Sync
on:
  schedule:
  - cron:  "0 16 * * *"
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
          workflow_token: ${{ secrets.WORKFLOW_TOKEN }}
        if: ${{ env.workflow_token != '' }}
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Sync from template
        uses: AndreasAugustin/actions-template-sync@v2
        env:
          workflow_token: ${{ secrets.WORKFLOW_TOKEN }}
        if: ${{ env.workflow_token != '' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: mementomoryn/rmm
          upstream_branch: main
          pr_labels: template_sync
          is_force_push_pr: true
