name: Merge Upstream
on: 
  schedule:
    - cron: '0 6 * * 2,4,6'
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync Repo
        run: gh repo sync ${{ github.repository }} -b testing -s revanced-apks/build-apps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
